create table if not exists public.game_runs (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(btrim(nickname)) between 1 and 12),
  play_mode text not null default 'pc' check (play_mode in ('pc', 'mobile')),
  stage1_ms bigint not null default 0 check (stage1_ms >= 0),
  stage2_ms bigint not null default 0 check (stage2_ms >= 0),
  stage3_ms bigint not null default 0 check (stage3_ms >= 0),
  total_ms bigint not null default 0 check (total_ms >= 0),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists game_runs_total_ms_idx
  on public.game_runs (total_ms asc, created_at asc);

alter table public.game_runs enable row level security;

drop policy if exists "Public leaderboard can be read" on public.game_runs;
create policy "Public leaderboard can be read"
  on public.game_runs for select
  to anon, authenticated
  using (true);

drop policy if exists "Players can submit a run" on public.game_runs;
create policy "Players can submit a run"
  on public.game_runs for insert
  to anon, authenticated
  with check (
    char_length(btrim(nickname)) between 1 and 12
    and play_mode in ('pc', 'mobile')
    and stage1_ms >= 0
    and stage2_ms >= 0
    and stage3_ms >= 0
    and total_ms >= 0
  );
